{% set name = "fbpca" %}
{% set version = "1.0" %}
{% set sha256 = "150677642479663f317fdbb5e06dab3f98721cf7031bb4a84113d7a631c472d1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - fbpca

about:
  home: https://github.com/facebook/fbpca
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Fast Randomized PCA/SVD

  description: |
    Functions for principal component analysis (PCA)
  doc_url: http://fbpca.readthedocs.org/
  dev_url: https://github.com/facebook/fbpca

extra:
  recipe-maintainers:
    - gully
    - pkgw
